      integer          nrec
      parameter      ( nrec =   101 )
      character*(40)   halfrec(2*nrec)
      data halfrec /
     &   "NAME",
     &   "",
     &   "       quack - Quincuncial Adaptive Clos",
     &   "ed Kohonen map",
     &   "",
     &   "",
     &   "SYNOPSIS",
     &   "",
     &   "       quack [OPTION]... DSK [FILE]...",
     &   "",
     &   "",
     &   "",
     &   "DESCRIPTION",
     &   "",
     &   "       Project arbitrary 3D points onto",
     &   "the QuACK map.",
     &   "",
     &   "",
     &   "       The first operand has to be the D",
     &   "igital Shape Kernel of a 160,000",
     &   "       plates QuACK shape model.",
     &   "",
     &   "",
     &   "",
     &   "       All subsequent operands are text",
     &   "files containing 3D points to",
     &   "       be projected, one vector per line",
     &   ". If option -4 or -l (mutually",
     &   "       exclusive, last one takes effect)",
     &   " is given (see below), additional",
     &   "       or different values are expected",
     &   "in each line. All spatial",
     &   "       dimensions are in kilometers.",
     &   "",
     &   "",
     &   "",
     &   "       When FILE is -, read standard inp",
     &   "ut.",
     &   "",
     &   "",
     &   "       Without any argument or with opti",
     &   "on --help, print this help",
     &   "       message and exit.",
     &   "",
     &   "",
     &   "",
     &   "OPTIONS",
     &   "",
     &   "       -1 FILE",
     &   "",
     &   "              Compute generalized longit",
     &   "udes and latitudes in degree and",
     &   "              write them to FILE. As thi",
     &   "rd value the elevation of the",
     &   "              original point relative to",
     &   " the QuACK shape model surface",
     &   "              is written to each line.",
     &   "",
     &   "",
     &   "",
     &   "       -2 FILE",
     &   "",
     &   "              Compute the 2D map coordin",
     &   "ates for hemispheres side by",
     &   "              side layout and write them",
     &   " to FILE. As third value the",
     &   "              elevation of the original",
     &   "point relative to the QuACK",
     &   "              shape model surface is wri",
     &   "tten to each line.",
     &   "",
     &   "",
     &   "       -3 FILE",
     &   "",
     &   "              Project the points onto th",
     &   "e surface of the QuACK shape model",
     &   "              and write the resultant 3D",
     &   " surface points to FILE. Behind",
     &   "              each 3D vector, the ID of",
     &   "the plate where the surface point",
     &   "              resides and the elevation",
     &   "of the original point relative",
     &   "              to the shape model surface",
     &   " are written in addition.",
     &   "",
     &   "",
     &   "       -4     Expect as input a file whi",
     &   "ch has previously been written",
     &   "              with option -3, providing",
     &   "plate ID and elevation behind",
     &   "              the 3D vector in each line",
     &   ". This is much faster.",
     &   "",
     &   "",
     &   "       -5 FILE",
     &   "",
     &   "              Compute the 2D map coordin",
     &   "ates for quincuncial layout with",
     &   "              the Northern hemisphere ce",
     &   "ntered and write them to FILE. As",
     &   "              third value the elevation",
     &   "of the original point relative",
     &   "              to the QuACK shape model s",
     &   "urface is written to each line.",
     &   "",
     &   "",
     &   "       -c TYPE",
     &   "",
     &   "              Write to standard output (",
     &   "console). The type of the output",
     &   "              to be computed is one of 1",
     &   ", 2, 3, 5, or s and corresponds",
     &   "              to the output requested by",
     &   " option -1, -2, -3, -5, or -s,",
     &   "              respectively.",
     &   "",
     &   "",
     &   "",
     &   "       -l     Expect as input in each li",
     &   "ne generalized longitude and",
     &   "              latitude in degree and ele",
     &   "vation relative to the QuACK",
     &   "              shape model surface. The e",
     &   "levation is just propagated to",
     &   "              the output and can safely",
     &   "be given as 0. Output option/type",
     &   "              3 is not supported with th",
     &   "is option.",
     &   "",
     &   "",
     &   "       -s FILE",
     &   "",
     &   "              Compute the 2D map coordin",
     &   "ates for quincuncial layout with",
     &   "              the Southern hemisphere ce",
     &   "ntered and write them to FILE. As",
     &   "              third value the elevation",
     &   "of the original point relative",
     &   "              to the QuACK shape model s",
     &   "urface is written to each line.",
     &   "",
     &   "",
     &   "       --help Print this help message an",
     &   "d exit.",
     &   "",
     &   "",
     &   "EXAMPLES",
     &   "",
     &   "       quack -5 quincuncial.txt chury_qu",
     &   "ack_tri_02_01.bds points.txt",
     &   "",
     &   "",
     &   "       Read 3D positions from file point",
     &   "s.txt and write the respective",
     &   "       coordinates on the QuACK map in q",
     &   "uincuncial layout to file",
     &   "       quincuncial.txt.",
     &   "",
     &   "",
     &   "",
     &   "       echo '2.442 -0.068 -0.345' | quac",
     &   "k chury_quack_tri_02_01.bds - -c5",
     &   "",
     &   "",
     &   "       Compute the QuACK map coordinates",
     &   " in quincuncial layout for the",
     &   "       point '2.442 -0.068 -0.345' and w",
     &   "rite the result to the console.",
     &   "       The result should be 0.685386121",
     &   "0.953147292 1.48380529E-02.",
     &   "",
     &   "",
     &   "       quack -3 onshape.txt quack chury_",
     &   "quack_tri_02_01.bds points.txt",
     &   "       quack -1 lonlat.txt -4 chury_quac",
     &   "k_tri_02_01.bds onshape.txt",
     &   "",
     &   "",
     &   "       First, read the positions from fi",
     &   "le poinst.txt, project",
     &   "       them onto the QuACK shape model,",
     &   "and write the results to",
     &   "       file onshape.txt. Second, read th",
     &   "e projected points from file",
     &   "       onshape.txt, compute generalized",
     &   "longitudes and latitudes, and",
     &   "       write them to file lonlat.txt.",
     &   "",
     &   "",
     &   "",
     &   "       Generalized longitudes and latitu",
     &   "des can be manipulated by other",
     &   "       means (e.g., rotated in order to",
     &   "create a traverse or oblique",
     &   "       aspect) and then fed back into qu",
     &   "ack:",
     &   "",
     &   "",
     &   "       quack -l5 quinc_traverse.txt chur",
     &   "y_quack_tri_02_01.bds lonlat.txt",
     &   "",
     &   ""/
